#!/usr/bin/env python3
"""
Compute expected arbitration statistics from CME-style PCAPs generated by pcap_gen.py.

This script does NOT call the C++ arbitrator.
It computes the expected results directly from the PCAPs.

It's output can be compared to the C++ arbitrator's output for validation.
"""

from scapy.all import rdpcap, Raw
import struct
import json
import sys
from collections import defaultdict


def extract_seq_and_timestamp(pkt):
    """
    Extract CME sequence number and Metamako timestamp.
    """
    if Raw not in pkt:
        return None, None

    data = bytes(pkt[Raw].load)

    if len(data) < 24:  # 4 bytes seq + 20 bytes trailer
        return None, None

    # Sequence number (little endian)
    seq = struct.unpack("<I", data[:4])[0]

    # Trailer offsets
    #Little-endian
    #sec = struct.unpack("<I", data[-12:-8])[0]
    #nsec = struct.unpack("<I", data[-8:-4])[0]

    #Big-endian : Metamako trailer is big-endian
    sec = struct.unpack(">I", data[-12:-8])[0]
    nsec = struct.unpack(">I", data[-8:-4])[0]


    timestamp_ns = sec * 1_000_000_000 + nsec
    return seq, timestamp_ns


def load_side(path):
    """
    Load a PCAP and return a dict: seq -> timestamp_ns
    """
    pkts = rdpcap(path)
    result = {}

    for pkt in pkts:
        seq, ts = extract_seq_and_timestamp(pkt)
        if seq is not None:
            result[seq] = ts

    return result


def compute_stats(sideA, sideB):
    """
    Compute arbitration statistics.
    """
    seqsA = set(sideA.keys())
    seqsB = set(sideB.keys())

    matched = seqsA & seqsB
    onlyA = seqsA - seqsB
    onlyB = seqsB - seqsA

    a_faster = 0
    b_faster = 0
    a_advantages = []
    b_advantages = []

    for seq in matched:
        tA = sideA[seq]
        tB = sideB[seq]
        diff = tB - tA  # positive = A faster

        if diff > 0:
            a_faster += 1
            a_advantages.append(diff)
        elif diff < 0:
            b_faster += 1
            b_advantages.append(-diff)

    def avg(lst):
        return sum(lst) / len(lst) if lst else 0.0

    overall = a_advantages + b_advantages

    return {
        "total_A": len(seqsA),
        "total_B": len(seqsB),
        "unmatched_A": len(onlyA),
        "unmatched_B": len(onlyB),
        "A_faster": a_faster,
        "B_faster": b_faster,
        "avg_A_adv_ns": avg(a_advantages),
        "avg_B_adv_ns": avg(b_advantages),
        "avg_overall_adv_ns": avg(overall),
    }


def main():
    if len(sys.argv) != 3:
        print("Usage: expected_stats.py SideA.pcap SideB.pcap")
        sys.exit(1)

    sideA_path = sys.argv[1]
    sideB_path = sys.argv[2]

    sideA = load_side(sideA_path)
    sideB = load_side(sideB_path)

    stats = compute_stats(sideA, sideB)

    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
